#Isaiah Hensley
#2024/4/22

A=input("Please enter your name: ")
B=input("Please enter your name: ")
C=input("Please enter your name: ")
D=input("Please enter your name: ")
E=input("Please enter your name: ")
F=input("Please enter your name: ")
G=input("Please enter your name: ")
H=input("Please enter your name: ")
I=input("Please enter your name: ")
J=input("Please enter your name: ")
K=input("Please enter your name: ")
L=input("Please enter your name: ")
M=input("Please enter your name: ")
N=input("Please enter your name: ")
O=input("Please enter your name: ")
P=input("Please enter your name: ")
Q=input("Please enter your name: ")
R=input("Please enter your name: ")
S=input("Please enter your name: ")
T=input("Please enter your name: ")

print(f"Here are the names that you listed: {A}")
print(B)
print(C)
print(D)
print(E)
print(F)
print(G)
print(H)
print(I)
print(J)
print(K)
print(L)
print(M)
print(N)
print(O)
print(P)
print(Q)
print(R)
print(S)
print(T)